### ISSUE TITLE
Links on the homepage - Evolution

### ISSUE THREAD

**Issue by lperamo** [lperamo/ecocomposer#32]
**Context**
Links should be underlined texts, not buttons. 
In the mean time, using links is sometimes not practical for people with deficiencies so big things are better.
(and more useful on mobiles for everyone)

**Solution**
Maybe we must use something like that instead:
```css
a {
  display         : flex;
  padding-bottom  : 4px;
  margin          : 5px auto;
  color           : #8dd737;
  text-decoration : none;
  border-bottom   : 2px solid #8dd737;
  width           : fit-content;
  font-size       : 22px;
  text-shadow     : 1px 1px #150;
  letter-spacing  : 1px;
}
```
